[tools]
elixir = "1.19"
erlang = "28"
node = "24"
python = "3.14"
bun = "latest"
cargo-binstall = "latest"
localstack = { version = "latest", exe = "localstack" }
lychee = "latest"
markdownlint-cli2 = "latest"
mongosh = "latest"
rust = "latest"
shfmt = "latest"
"npm:diff2html-cli" = "latest"
"npm:zenn-cli" = "latest"
"pipx:basic-memory" = "latest"
"pipx:cargo-lambda" = "latest"

[env]
ERL_AFLAGS = "-kernel shell_history enabled"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "ruby"]
